# Realm Swift's SwiftLint configuration file
# Uncomment the commented lines to avoid any violations

included:
  - RealmSwift
disabled_rules:
  - force_cast
  - todo
line_length:
  - 120
file_length:
  - 670
type_body_length:
  - 581
